### ISSUE TITLE
[Bug] Unhandled errors in Content Retrieval appears to halt queue operations

### ISSUE THREAD

**Issue by godver3** [godver3/cli_debrid#229]

**Comment by godver3** [comment]
```
2024-09-14 08:18:13,532 - metadata.py:process_metadata:326 - WARNING - Could not find IMDb ID for item: {'tmdb_id': 260685, 'media_type': 'tv'}

2024-09-14 08:18:29,218 - metadata.py:get_overseerr_show_episodes:177 - ERROR - Error fetching show episodes for TMDB ID 258931, season 1: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Exception in thread Thread-194 (start):

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner

    self.run()

  File "/usr/local/lib/python3.11/threading.py", line 982, in run

    self._target(*self._args, **self._kwargs)

  File "/app/run_program.py", line 302, in start

    self.run()

  File "/app/run_program.py", line 314, in run

    self.process_queues()

  File "/app/run_program.py", line 155, in process_queues

    self.process_content_source(source, data)

  File "/app/run_program.py", line 215, in process_content_source

    processed_items = process_metadata(items)

                      ^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/metadata/metadata.py", line 393, in process_metadata

    available_episodes = season_details.get('episodes', [])

                         ^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'get'

```
